local str = require('str')

describe('str', function()
  describe('strip', function()
    it('should strip the pattern', function()
      assert.is_equal('sh', str.strip('ba', 'bash'))
    end)
  end)

  describe('replace', function()
    it('should replace the pattern with the replacement string', function()
      assert.is_equal('%2C', str.replace('%%..', string.upper, '%2c'))
    end)
  end)
end)
